export default {
  LOAD_SEARCHED_MOVIES: 'LOAD_SEARCHED_MOVIES',
  LOAD_MOVIE_DETAILS: 'LOAD_MOVIE_DETAILS',
  LOAD_FAVOURITE_MOVIES: 'LOAD_FAVOURITE_MOVIES',
  LOAD_TOP_MOVIES: 'LOAD_TOP_MOVIES',
  DELETE_FAVOURITE_MOVIES: 'DELETE_FAVOURITE_MOVIES',
  ADD_FAVOURITE_MOVIES: 'ADD_FAVOURITE_MOVIES',
  LOAD_CREDITS_DETAILS: 'LOAD_CREDITS_DETAILS'
};
